misitio/urls.py
from pasteleria.models import Cliente, Comuna, Producto
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from misitio import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'Clientes', views.ClienteViewSet)
router.register(r'Comunas', views.ComunaViewSet)
router.register(r'Productos', views.ProductoViewSet)
router.register(r'groups', views.GroupViewSet)
urlpatterns = [
    path('pasteleria/', include('pasteleria.urls')),
    path('admin/', admin.site.urls),
    
    path('api', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

pasteleria/urls.py
from django.urls import path

from . import views
app_name = 'pasteleria'
urlpatterns = [
    path('', views.index, name='index'),
    path('home', views.home, name='home'),
    path('torta', views.torta, name='torta'),
    path('pedido', views.pedido, name='pedido'),
    path('frm_iniciar_sesion', views.frm_iniciar_sesion, name='frm_iniciar_sesion'),
    path('iniciar_sesion', views.iniciar_sesion, name='iniciar_sesion'),
    path('frm_registrar_cli', views.frm_registrar_cli, name='frm_registrar_cli'),
    path('registrar_cliente', views.registrar_cliente, name='registrar_cliente'),
    path('cliente_regitrado', views.cliente_regitrado, name='cliente_regitrado' ),
    path('frm_buscar_cliente', views.frm_buscar_cliente, name='frm_buscar_cliente'),
    path('buscar_y_mostrar_cliente', views.buscar_y_mostrar_cliente, name='buscar_y_mostrar_cliente'),
    path('eliminar_cliente', views.eliminar_cliente, name='eliminar_cliente'),
    path('eliminador_cliente', views.eliminador_cliente, name='eliminador_cliente'),
    path('editar_cliente', views.editar_cliente, name='editar_cliente'),
    path('editador_cliente', views.editador_cliente, name='editador_cliente'),
    path('frm_comuna', views.frm_comuna, name='frm_comuna'),
    path('registrar_comuna', views.registrar_comuna, name='registrar_comuna'),
    path('frm_buscar_comuna', views.frm_buscar_comuna, name='frm_buscar_comuna'),
    path('buscar_y_mostrar_comuna', views.buscar_y_mostrar_comuna, name='buscar_y_mostrar_comuna'),
    path('eliminar_comuna', views.eliminar_comuna, name='eliminar_comuna'),
    path('eliminador_comuna', views.eliminador_comuna, name='eliminador_comuna'),
    path('editar_comuna', views.editar_comuna, name='editar_comuna'),
    path('editador_comuna', views.editador_comuna, name='editador_comuna'), 
    path('frm_producto', views.frm_producto, name='frm_producto'),
    path('registrar_producto', views.registrar_producto, name='registrar_producto'),
    path('frm_buscar_producto', views.frm_buscar_producto, name='frm_buscar_producto'),
    path('buscar_y_mostrar_producto', views.buscar_y_mostrar_producto, name='buscar_y_mostrar_producto'),
    path('eliminar_producto', views.eliminar_producto, name='eliminar_producto'), 
    path('eliminador_producto', views.eliminador_producto, name='eliminador_producto'),
    path('editar_producto', views.editar_producto, name='editar_producto'),
    path('editador_producto', views.editador_producto, name='editador_producto'),
]

pasteleria/models.py
from django.db import models
from django.db.models.base import Model
from django.utils.translation import ugettext as _
# Create your models here.
class Producto(models.Model):
    nombre_pro =  models.CharField(max_length=50,default='')
    precio_pro = models.IntegerField(default=0)
    def __str__(self):
        return self.nombre_pro
    class Meta:
        permissions = (
            ( 'gerente', _('Es gerente') ),
            ( 'cocinero', _('Es cocinero') ),
        )

class Comuna(models.Model):
    nombre_c =  models.CharField(max_length=50,default='')
    def __str__(self):
        return self.nombre_c

class Cliente(models.Model):
    rut =  models.CharField(max_length=13)
    nombre_cli = models.CharField(max_length=50,default='')
    apellido_cli = models.CharField(max_length=50,default='')
    fecha_nac = models.DateTimeField('Fecha de nacimiento del cliente')
    correo = models.CharField(max_length=50)
    direccion = models.CharField(max_length=100, default=' ')
    comuna = models.ForeignKey(Comuna, on_delete=models.CASCADE, default=' ')
    contrasena = models.CharField(max_length=50)
    contrasena_val = models.CharField(max_length=50)
    def __str__(self):
        return self.rut
    

pasteleria/views.py
from django.shortcuts import render
from django.http import HttpResponse, response, HttpResponseRedirect
from django.shortcuts import render
from pasteleria.models import Cliente, Comuna, Producto
from django.utils import timezone
from django.urls import reverse
import re
import sys
from itertools import cycle
from django.contrib.auth import authenticate, login
# Create your views here.
 
def index(request):

    return render(request, 'pasteleria/index.html',)
def home(request):

    return render(request, 'pasteleria/home.html',)
def frm_iniciar_sesion(request):
    return render(request, 'pasteleria/frm_iniciar_sesion.html',)
def iniciar_sesion(request):
    usuario = request.POST["nombre_user"]
    clave = request.POST["contrasena_user"]

    user = authenticate(request, username=usuario, password=clave)

    if user is not None:
        login(request, user)
        #return HttpResponse(user.username)
        nombre = user.first_name + " " + user.last_name
        return render(request, 'pasteleria/usuario_correcto.html',)
        #return HttpResponseRedirect(reverse('panaderia:index'))
    else:
        return render(request, 'pasteleria/error_usuario.html',)

def frm_registrar_cli(request):
    comuna = Comuna.objects.all()
    carrito = {'comuna':comuna}
    return render(request, 'pasteleria/frm_registrar_cli.html', carrito,)
def torta(request):
    return render(request, 'pasteleria/torta.html',)
def pedido(request):
    return render(request, 'pasteleria/pedido.html',)
def registrar_cliente(request): 
    error = 'Error en el ingreso del'
    v_error = False
    primer_erro = False 
    rut_c = request.POST['rut']
    rut_c = rut_c.replace(' ','')
    rut_c = rut_c.replace('.','')
    rut_c = rut_c.replace('.','')
    rut_c = rut_c.replace('-','')
    
    nombre = request.POST['nombre']
    nombre = nombre.replace(' ','')
    apellido = request.POST['apellido'] 
    apellido = apellido.replace(' ','')
    fecha = request.POST['Fecha_nacimiento']  
    dirrecion = request.POST['dirrecion']
    comuna = request.POST['comuna']  
    correo= request.POST['correo']    
    correo = correo.replace(' ','')
    contrasena= request.POST['contrasena'] 
    contrasena= nombre.replace(' ','')   
    validar_contrasena= request.POST['validar_contrasena']    
    cantidad = len(rut_c)

    if request.POST['contrasena'] != request.POST['validar_contrasena']:
        return render(request, 'pasteleria/error_contrase.html')
    if(fecha =="" or apellido =="" or correo =="" or nombre =="" or contrasena =="" or rut_c =="" or dirrecion=="" or comuna ==""):
        return render(request, 'pasteleria/error_ingreso.html')
    if cantidad < 8:
        return render(request, 'pasteleria/error_ingreso.html')
    if cantidad > 10:
        return render(request, 'pasteleria/error_ingreso.html')
    aux = rut_c[:-1]
    dv = rut_c[-1:]
 
    revertido = map(int, reversed(str(aux)))
    factors = cycle(range(2,8))
    s = sum(d * f for d, f in zip(revertido,factors))
    res = (-s)%11
 
    if str(res) == dv:
        v_error = True
    elif dv=="K" and res==10:
        v_error = True
    else:
        v_error = False
    if v_error == False:
        return render(request,'pasteleria/error_rut.html')
    com = Comuna.objects.get(id=comuna)
    

    cliente =Cliente(rut= rut_c, nombre_cli=nombre, apellido_cli=apellido, fecha_nac=fecha, correo=correo, direccion=dirrecion, comuna=com, contrasena=contrasena, contrasena_val=validar_contrasena)
    cliente.save()
    return HttpResponseRedirect(reverse('pasteleria:cliente_regitrado'))


def cliente_regitrado(request):
    return render(request,'pasteleria/cliente_regitrado.html')

def frm_buscar_cliente(request):
    return render(request,'pasteleria/frm_buscar_cliente.html')

def buscar_y_mostrar_cliente(request):
    rut_b = request.POST['rut_b']
    rut_b = rut_b.replace('.','')
    rut_b = rut_b.replace('.','')
    rut_b = rut_b.replace('-','')

    listado =  Cliente.objects.filter(rut__startswith=rut_b)   
    
    carrito = {'listado':listado}
    return render(request, 'pasteleria/mostrar_cliente.html',carrito)
    
   
def eliminar_cliente(request):
    eliminador = Cliente.objects.get(id= request.POST['id_e'])
    eliminar_mostrar = {'eliminador':eliminador}
    return render(request, 'pasteleria/eliminar_cliente.html',eliminar_mostrar)
def eliminador_cliente(request):
    elim =  Cliente.objects.get(id= request.POST['id_eliminado'])
    elim.delete()
    return render(request, 'pasteleria/cliente_eliminado.html',)
def editar_cliente(request):
    editar =  Cliente.objects.get(id= request.POST['id_d'])
    comuna = Comuna.objects.all()
    editar_mostrar ={'editar': editar,'comuna':comuna}
    
      
    return render(request, 'pasteleria/editar_cliente.html',editar_mostrar, )
def editador_cliente(request):
    e = Cliente.objects.get(id= request.POST['id_editor'])
    rut_c = request.POST['rut_editor']
    rut_c = rut_c.replace(' ','')
    nombre = request.POST['nombre_editor']
    nombre = nombre.replace(' ','')
    apellido = request.POST['apellido_editor'] 
    apellido = apellido.replace(' ','')
    fecha = request.POST['Fecha_nacimiento_editor']  
    correo= request.POST['correo_editor']    
    correo = correo.replace(' ','')
    dirrecion = request.POST['dirrecion']
    comuna = request.POST['comuna'] 
    contrasena= request.POST['contrasena_editor'] 
    contrasena = contrasena.replace(' ','')   
    validar_contrasena= request.POST['validar_contrasena_editor']
    if request.POST['contrasena_editor'] != request.POST['validar_contrasena_editor']:
        return HttpResponse('las contraseñas deben ser iguales')
    if(fecha =="" or apellido =="" or correo =="" or nombre =="" or contrasena =="" or rut_c ==""):
        return render(request, 'pasteleria/error_ingreso.html')
    if len(request.POST['rut_editor']) < 8 and len(request.POST['rut_editar']) < 10:
        return render(request, 'pasteleria/error_ingreso.html')
    aux = rut_c[:-1]
    dv = rut_c[-1:]
 
    revertido = map(int, reversed(str(aux)))
    factors = cycle(range(2,8))
    s = sum(d * f for d, f in zip(revertido,factors))
    res = (-s)%11
 
    if str(res) == dv:
        v_error = True
    elif dv=="K" and res==10:
        v_error = True
    else:
        v_error = False
    if v_error == False:
        return render(request,'pasteleria/error_rut.html')
    com = Comuna.objects.get(id=comuna)
    
    e.rut = rut_c
    e.nombre_cli = nombre
    e.apellido_cli = apellido
    e.fecha_nac = fecha
    e.correo = correo
    e.direccion = dirrecion
    e.comuna = com
    e.contrasena = contrasena
    e.contrasena_val = validar_contrasena

    e.save()
    return render(request, 'pasteleria/editar_c.html',)   

def frm_comuna(request):
    return render(request, 'pasteleria/frm_comuna.html', )
def registrar_comuna(request):
    nombre_com = request.POST['nombre_comuna']
    nombre_com = nombre_com.replace(' ','')
    if(nombre_com ==""):
        return render(request, 'pasteleria/error_ingreso.html',)  
    comuna = Comuna(nombre_c=nombre_com)
    comuna.save()
    return render(request, 'pasteleria/comuna_registrado.html',)


def frm_buscar_comuna(request):
    return render(request,'pasteleria/frm_buscar_comuna.html')
def buscar_y_mostrar_comuna(request):
    nombre_c = request.POST['nombre_buscar']

    listado =  Comuna.objects.filter(nombre_c__startswith=nombre_c)   
    
    carrito = {'listado':listado} 
    return render(request, 'pasteleria/mostrar_comuna.html',carrito)
def eliminar_comuna(request):
    eliminador = Comuna.objects.get(id= request.POST['id_e'])
    eliminar_mostrar = {'eliminador':eliminador}
    return render(request, 'pasteleria/eliminar_comuna.html',eliminar_mostrar)
def eliminador_comuna(request):
    elim =  Comuna.objects.get(id= request.POST['id_eliminado'])
    elim.delete()
    return render(request, 'pasteleria/comuna_eliminado.html',)
def editar_comuna(request):
    comuna =  Comuna.objects.get(id= request.POST['id_d'])
    editar_mostrar ={'comuna':comuna}  
    return render(request, 'pasteleria/editar_comuna.html',editar_mostrar, )

def editador_comuna(request):
    e = Comuna.objects.get(id= request.POST['id_editor'])
    nombre_com = request.POST['nombre_editor']
    nombre_com = nombre_com.replace(' ','')
    if(nombre_com ==""):
        return render(request, 'pasteleria/error_ingreso.html',)  
    e.nombre_c = nombre_com
    e.save()
    return render(request, 'pasteleria/comuna_registrado.html',) 

def frm_producto(request):
    return render(request, 'pasteleria/frm_producto.html', )
def registrar_producto(request):
    nombre_com = request.POST['nombre_producto']

    precio = request.POST['precio_producto']
    if(nombre_com =="" or precio == 0 ):
        return render(request, 'pasteleria/error_ingreso.html',)  
    if request.user.has_perm('pasteleria.cocinero'):
        p = Producto(nombre_pro=nombre_com, precio_pro=precio)
        p.save()
        return render(request, 'pasteleria/producto_registrado.html',) 
    else:
         return render(request, 'pasteleria/falta_credenciales.html',) 
def frm_buscar_producto(request):
    return render(request,'pasteleria/frm_buscar_producto.html')
def buscar_y_mostrar_producto(request):
    nombre_p = request.POST['nombre_buscar']

    listado =  Producto.objects.filter(nombre_pro__startswith=nombre_p)   
    
    carrito = {'listado':listado} 
    return render(request, 'pasteleria/mostrar_producto.html',carrito)
def eliminar_producto(request):
    eliminador = Producto.objects.get(id= request.POST['id_e'])
    eliminar_mostrar = {'eliminador':eliminador}
    return render(request, 'pasteleria/eliminar_producto.html',eliminar_mostrar)    
def eliminador_producto(request):
    elim =  Producto.objects.get(id= request.POST['id_eliminado'])
    elim.delete()
    return render(request, 'pasteleria/producto_eliminado.html',)
def editar_producto(request):

pasteleria/templates/pasteleria/editar_comuna.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/style_nuestro.css' %}">
<div>
    <nav class="navbar navbar-expand-lg  color_menu">
        <div class="container">
            <img id="imagen" class="logo" src="{% static 'pasteleria/img/logo_cafe.png' %}">
            <a class="navbar-brand color_letar" href="{% url 'pasteleria:index' %}">Cake House</a>
            <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link color_letar" href="{% url 'pasteleria:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link color_letar" href="{% url 'pasteleria:torta' %}">Producto<span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link color_letar" href="#">Registrarse</a>
                    </li>


                    <a class="nav-link color_letar" href="{% url 'pasteleria:frm_iniciar_sesion' %}">Iniciar sesion</a>
                    </li>


                    </li>
                </ul>
            </div>
    </nav>
</div>
<div class="container col-sm-7 mt-2 frm_comuna">
    <h1 class="centrar">Editar Comuna</h1>
<form action="{% url 'pasteleria:editador_comuna' %}" method="post">
    {% csrf_token %}
    <div class="row mover_I_25">
        <h5 class="col-sm-2 mt-1">comuna:</h5>
    <input type="text" name="id_editor" value="{{comuna.id}}" hidden>
    <br>
    <input type="text" id="nombre_ce" class="col-sm-4 form-control" name="nombre_editor" required value="{{comuna.nombre_c}}" >
    <div id="error_c" style="color: red; visibility: hidden;" class="error">*Debe ingresar comuna</div>
    </div>

    <input type="submit" id="Guardar_ec" class="btn btn-primary boton_com"  value="   editar   ">
</form>
</div><div class="boton_com row" style="margin-left: 23%;">
<div class="  btn btn-primary col-sm-4">
<a class=" color_letra" href="{% url 'pasteleria:index' %}">volver a pagina inicial</a>
</div>
<div class=" ml-1 btn btn-primary col-sm-4">
<a class=" color_letra" href="{% url 'pasteleria:frm_buscar_comuna' %}">volver al buscador</a>
</div>
</div>
<script type="text/javascript" src="{% static 'pasteleria/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'pasteleria/js/jquery-3.6.0.min.js' %}"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#Guardar_ec").click(function () {
            var nombre = $("#nombre_ce").val();
            if (nombre == "") {
                $("#error_c").css("visibility", "visible")
                return false;
            }
            else {
                return true;
            }

        });
        });

</script>

pasteleria/templates/pasteleria/editar_producto.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/style_nuestro.css' %}">
<div>
    <nav class="navbar navbar-expand-lg  color_menu">
        <div class="container">
            <img id="imagen" class="logo" src="{% static 'pasteleria/img/logo_cafe.png' %}">
            <a class="navbar-brand color_letar" href="{% url 'pasteleria:index' %}">Cake House</a>
            <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link color_letar" href="{% url 'pasteleria:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link color_letar" href="{% url 'pasteleria:torta' %}">Producto<span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link color_letar" href="#">Registrarse</a>
                    </li>


                    <a class="nav-link color_letar" href="{% url 'pasteleria:frm_iniciar_sesion' %}">Iniciar sesion</a>
                    </li>


                    </li>
                </ul>
            </div>
    </nav>
</div>
<div class="container col-sm-7 mt-2 frm_comuna">
    <h1 class="centrar">Editar producto</h1>
<form action="{% url 'pasteleria:editador_producto' %}" method="post">
    {% csrf_token %}
    <div class="row mover_I_25">
    <input type="text" name="id_editor" value="{{producto.id}}" hidden>
    <h5 class="col-sm-2 mt-1">Producto:</h5>
    
    <input type="text" id="producto_e" class="col-sm-4 form-control" name="nombre_editor" value="{{producto.nombre_pro}}" required >
    <div id="error_ce" style="color: red; visibility: hidden;" class="error">*Debe ingresar Producto</div>
    </div>
    <div class="row mover_I_25">
        <h5 class="col-sm-2 mt-1">Precio:</h5>
    <input type="number" id="precio_e" class="col-sm-4 form-control"  name="precio_editor" value="{{producto.precio_pro}}" required>
    <div id="error_pe" style="color: red; visibility: hidden;" class="error">*Debe ingresar precio</div>
    </div>

    <input type="submit" id="Guardar_pe"  class="btn btn-primary boton_com" value="editar">
</form>
</div>
<div class="boton_com row" style="margin-left: 20%;">
<div class="  btn btn-primary col-sm-4">
<a class=" color_letra" href="{% url 'pasteleria:index' %}">volver a pagina inicial</a>
</div>
<div class="  col-sm-1 "> </div>
<div class="  btn btn-primary col-sm-4 ">
<a class=" color_letra" href="{% url 'pasteleria:frm_buscar_comuna' %}">volver al buscador</a></div>
</div>

<script type="text/javascript" src="{% static 'pasteleria/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'pasteleria/js/jquery-3.6.0.min.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#Guardar_pe").click(function () {
            var producto = $("#producto_e").val();
            var precio = $("#precio_e").val();
            
            if (precio == "") {
                $("#error_pe").css("visibility", "visible")
                return false;
            }

            else {
                $("#error_pe").css("visibility", "hidden")
              
            }
            if (precio <= 0) {
                $("#error_pe").css("visibility", "visible")
                return false;
            }
            else {
                $("#error_pe").css("visibility", "hidden")
            }
            if (producto == "") {
                $("#error_ce").css("visibility", "visible")
                return false;
                
            }
            else {
             
                $("#error_c").css("visibility", "hidden")
                return true;
               
            }
          

        });
        });

</script>

pasteleria/templates/pasteleria/eliminar_cliente.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/style_nuestro.css' %}">
<div>
    <nav class="navbar navbar-expand-lg  color_menu">
        <div class="container">
            <img id="imagen" class="logo" src="{% static 'pasteleria/img/logo_cafe.png' %}">
            <a class="navbar-brand color_letar" href="{% url 'pasteleria:index' %}">Cake House</a>
            <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link color_letar" href="{% url 'pasteleria:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link color_letar" href="{% url 'pasteleria:torta' %}">Producto<span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link color_letar" href="#">Registrarse</a>
                    </li>


                    <a class="nav-link color_letar" href="{% url 'pasteleria:frm_iniciar_sesion' %}">Iniciar sesion</a>
                    </li>


                    </li>
                </ul>
            </div>
    </nav>
</div>
<div class="container col-sm-7 mt-2 frm_comuna" style="margin-bottom: 10%;"> 
    <h1 class="centrar color_letar">Ingresar Cliente</h1>
<form action="{% url 'pasteleria:eliminador_cliente' %}" method="post">
    {% csrf_token %}
    <div class="row mover_I_25" style="margin-left: 5%; margin-right: 10%;">
    <input type="text" name="id_eliminado" value="{{eliminador.id}}" hidden>
    <h5 class="col-sm-2 mt-1 color_letar">rut:</h5>
    <input type="text" class="col-sm-4 form-control" name="rut_e" value="{{eliminador.rut}}"  disabled>
    <h5 class="col-sm-2 mt-1 color_letar">nombre:</h5>
    <input type="text" name="nombre_e" class="col-sm-4 form-control" value="{{eliminador.nombre_cli}}" disabled>
    </div>
    <div class="row mover_I_25" style="margin-left: 5%; margin-right: 10%;">
        <h5 class="col-sm-2 mt-1 color_letar">apellido:</h5>
        <input type="text" class="col-sm-4 form-control" name="apellido_e"value="{{eliminador.apellido_cli}}" disabled>
        <h5 class="col-sm-2 mt-1 color_letar">dirrecion:</h5>
    <input type="text" class="col-sm-4 form-control" name="dirrecion" value="{{eliminador.direccion}}" disabled>
    <br></div>
    <div class="row mover_I_25" style="margin-left: 5%; margin-right: 10%;">
    <h5 class="col-sm-2 mt-1 color_letar">comuna:</h5>
    <input type="text" class="col-sm-4 form-control" name="comuna" value="{{eliminador.comuna}}" disabled>
    <h5 class="col-sm-2 mt-1 color_letar">fecha:</h5>
    <input type="text" class="col-sm-4 form-control" name="Fecha_nacimiento_e" value="{{eliminador.fecha_nac}}" disabled>
    </div>
    <div class="row mover_I_25" style="margin-left: 5%; margin-right: 10%;">
        <h5 class="col-sm-2 mt-1 color_letar">Correo:</h5>
    <input type="text" class="col-sm-4 form-control" name="correo_e" value="{{eliminador.correo}}" disabled>
    <h5 class="col-sm-2 mt-1 color_letar">Contraseña:</h5>
    <input class="col-sm-4 form-control" type="password" value="{{eliminador.contrasena}}" disabled >
    </div>
    
    <input type="submit"class="btn btn-primary  boton_com"  value="eliminar">
</form><div class="row mover_I_25" style="margin-left: 5%; margin-right: 10%;"> 
    <a class="btn btn-primary "  style="margin-left: 20%; margin-bottom: 5%;" href="{% url 'pasteleria:index' %}">volver a pagina inicial</a>
   
    <a  class="btn btn-primary  " style="margin-left: 20%; margin-bottom: 5%;" href="{% url 'pasteleria:frm_buscar_cliente' %}">volver al buscador</a>
</div>
</div> 

pasteleria/templates/pasteleria/frm_buscar_producto.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'pasteleria/css/style_nuestro.css' %}">
<div>
    <nav class="navbar navbar-expand-lg  color_menu">
        <div class="container">
            <img id="imagen" class="logo" src="{% static 'pasteleria/img/logo_cafe.png' %}">
            <a class="navbar-brand color_letar" href="{% url 'pasteleria:index' %}">Cake House</a>
            <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link color_letar" href="{% url 'pasteleria:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link color_letar" href="{% url 'pasteleria:torta' %}">Producto<span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link color_letar" href="#">Registrarse</a>
                    </li>


                    <a class="nav-link color_letar" href="{% url 'pasteleria:frm_iniciar_sesion' %}">Iniciar sesion</a>
                    </li>


                    </li>
                </ul>
            </div>
    </nav>
</div>
<div class="container col-sm-7 mt-4 frm_comuna">
<h1 class="centrar">Buscar Producto</h1>
<form action="{% url 'pasteleria:buscar_y_mostrar_producto' %}" method="POST">
    {% csrf_token %}
    <div class="row mover_I_25">
        <h4 col-sm-2 mt-2>nombre:</h4>
    <input type="text" name="nombre_buscar" class="col-sm-4 ml-1 form-control" placeholder="torta de chocolate">
    </div>
    <input type="submit" class="btn btn-primary  boton_com" value="Buscar">
    
</form>
</div>